// list of prompts
// _ - " borrowed " - _ from:
// https://colab.research.google.com/drive/1GtyVgVCwnDfRvfsHbeU0AlG-SgQn1p8e?usp=sharing#scrollTo=gbfhp-raJgPH

export default class p {}
export const prompts_list = [
  "an oil tanker drydock constructed in a field in the countryside by John Constable and Tyler Edlin, artstation",
  "ww1 warship in drydock near an European village countryside landscape by Casper David Friedrich, artstation",
  "cossacks marching near a warship in the countryside landscape by Tyler Edlin and Caspar David Friedrich, artstation",
  "a crashed warship, a fishing village on the river in a mountain landscape by Casper David Friedrich, warship on artstation, mountain landsape on artstation, village on artstation",
  "a flower field landscape, an abandoned building in a field, a mural of flowers on the side of an abandoned building, a rusty car, trending on artstation, cinematic lighting, vibrant",
  "a shipwreck on a sci-fi alien desert landscape, german romanticism, artstation, digital art, magical realism, moody palette, contrasting",
  "shipwreck on a twisted alien landscape, abandoned twisted alien landscape by Casper David Friedrich, whispy clouds, planets and stars in the sky, artstation",
  "a flower field landscape, an abandoned castle in a field, a mural of flowers on the side of an abandoned castle, petals flying in the breeze, butterflies, artstation, cinematic lighting, vibrant",
  "an abandoned skyscraper in a field of flowers, petals flying in the breeze, flowers made of metal shards, cinematic lighting, vibrant",
  "an abandoned skyscraper in a field in an autumn pastoral landscape, cinematic lighting, vibrant, surrealism, deviantart",
  "an abandoned boat in a frozen winter wonderland lake, snowflakes drifting in the breeze, impressionism, magical realism",
  "a sailboat docked at a boathouse, snowflakes drifting in the breeze, cinematic lighting, vibrant, winter wonderland",
  "an abandoned building in a field of flowers landscape by caspar david friedrich and RHADS, artstation, cinematic lighting",
  "an iridescent cottage on a crumbling cliffside by the sea, by Tyler Edlin and Andreas Rocha, deviantart, digital painting",
  "a surreal digital art illustraiton of an abandoned castle in a field of flowers landscape by Victo Ngai, flowers, butterflies",
  "a glowing obelisk on a mountain by Alejandro Burdisio and Tyler Edlin and RHADS, digital paintnig, award-winning",
  "ruins of an abandoned medieval city in wasteland landscape by Felix Kelly and Richard Anderson, oil on canvas, american romanticism",
  "an abandoned city in a tropical swamp landscape by Gediminas Pranckevicius and Jacek Yerka, murals of tropical flowers, artstation, vibrant, cinematic lighting",
  "an abandoned city in a lakes and field of flowers landscape, oil on canvas, award-winning, textured, moody palette, deviantart",
  "an abandoned building in a field of flowers by Jean Delville and Thomas Kinkade, a mural of flowers on an abandoned building, highly detailed matte painting, vibrant",
  "an abandoned cathedral in a field of flowers by Jean Delville and John Atkinson Grimshaw, highly detailed matte painting, german romanticism",
  "streets of the abandoned city overgrown with blooming vines by Jean Delville and John Atkinson Grimshaw and Gilbert Williams, concept art",
  "lightning storm over the grand canyon, dramatic scenery, cinematic lighting, graphic illustration, by Gilbert Williams and RHADS",
  "swirling green plasma, infinite celestial sea of darkness, deviantart, digital art, contrasting, simple subject",
  "swarm of green fireflies over a dark nightscape landscape by Gilbert Williams and Beeple, digital painting, award winning, artstation",
  "a dark wizard tower photographed by ansel adams and painted by RHADS, oil on canvas",
  "an aquarium in a dimly lit room, abandoned industrial room, low hanging flourescent light, digital painting, contest-winner",
  "an aquarium in a dimly lit abandoned industrial room, low hanging fluorescent light, artstation",
  "imposing glowing sci-fi neon obelisks on a snowy landscape, falling snow, oil on canvas, artstation",
  "60's mainframes in a dimly lit abandoned industrial room, low hanging fluorescent light, digital art, clean, dark, high-contrast, moody palette",
  "60's mainframes in a dimly lit abandoned industrial room, face renders on computer screens with face renders, low hanging fluorescent light, trending on artstation",
  "a cylinder aquarium in a dimly lit abandoned warehouse, low hanging fluorescent light, lab equipment, trending on artstation",
  "a tropical aquarium in a dimly lit abandoned atrium, skylights, trending on artstation, steampunk",
  "an aquarium in an atrium, a crowd gathers, skylights, trending on artstation, steampunk, victorian",
  "a panel aquarium in a dim abandoned warehouse, low hanging fluorescent light, artstation, digital art, 35mm photograph",
  "abandoned cyberpunk lab, an aquarium in a dimly lit cyberpunk lab, low hanging fluorescent light, by Syd Mead and James Turrell",
  "intricate crumbling ivy covered wall by claude monet, detailed impressionism painting, artstation",
  "a majestic dieselpunk battlemech standing near a russian orthodox church on a snowing landscape, by Gilbert Williams and Barclay Shaw, concept art",
  "an imposing dieselpunk mech in the autumn countryside by Ivan Aivazovsky and Greg Rutkowski, trending on artstation, cinematic lighting",
  "an imposing clockwork elephant mech on an arctic landscape by Ivan Aivazovsky and Greg Rutkowski, digital painting, highly detailed, award winning concept art",
  "a space marine bear by Ivan Aivazovsky and Greg Rutkowski, warhammer 40k",
  "a space marine bear by george stubbs and greg rutkowski, warhammer 40k, illustration",
  "post-industrial smokestacks on lava flows across the wasteland with belching smoke filling the sky, red lighting lacing the clouds, by Ivan Aivazovsky and Greg Rutkowski, artstation",
  "giant sinister twisted rose vines cover the wizard tower in the forest by tyler edlin and gilbert williams, highly detailed matte painting, surrealism ",
  "an imposing lighthouse in a nebula by tyler edlin and RHADS, artstation, oil on canvas, magical realism, science fiction concept art",
  "a beautiful painting of a circular portal opening to a flower ocean dimension embedded in an asteroid floating in a nebula by RHADS, trending on deviantart, vibrant",
  "a beautiful painting of a tree on an asteroid in a vast nebula by Albert Bierstadt and Tyler Edlin and RHADS",
  "a painting of an ancient magical mystical willow tree on an asteroid in a vast nebula by Tyler Edlin and RHADS and Gilbert Williams",
  "a stunning portrait of a woman pondering the wilderness by RHADS and Gilbert Williams, artstation, digital painting",
  "an abandoned building on an asteroid in a vast nebula by Tyler Edlin and John Harris and Hubert Robert, concept art, impressionism, watercolor",
  "a spanish galleon sailing on a vast and beautiful nebula by ivan aivazovsky and John Harris, celestial sea",
  "a beautiful painting of a sailboat sailing on a nebula by RHADS and Gilbert Williams, deviantart",
  "whales swimming through vast and beautiful clouds by RHADS and Ross Tran and Albert Bierdstat, artstation, god rays, surrealism",
  "inside an abandoned 1980's mall, retrowave, 35mm photograph, Memphis Design, HD photograph, octane soft render",
  "empty waiting room with yellow wallpaper, found photograph, by ansel adams, washed out color",
  "empty unsettling waiting room with yellow wallpaper, 3d room render, trending on artstation",
  "an imposing mech standing in a wheat field on an overcast summer day by john constable, artstation",
  "a beautiful painting of an abandoned rusty cyberpunk city, neon signs, in the style of syd mead and greg rutkowski, artstation",
  "an abandoned and decaying city screenprint by dan mumford, cuberpunk style, blinking neon signs, artstation",
  "a illustration of a diner on the street corner of a rusty cyberpunk city, neon signs, trending on artstation",
  "a diorama of colorful soil layers, waterfalls between layers over the wooden buildings between the layers, magic realism painting by Alexander Jansson and machinarium",
  "on the streets of the ancient city sinking into the briny deep by Tyler Edlin, artstation, vivid, vibrant",
  "Zoroastrian towers on a desert landscape by Andreas Rocha and Hubert Robert, digital art, magical realism, fantasy concept art",
  "portrait of the devine cybernetic angel by Peter Mohrbacher and Ross Tran, character design, octane soft render, cyberpunk",
  "empress of clockwork spacetime painted by Peter Mohrbacher and Ross Tran",
  "stunning beautiful portrait of clockwork singularity princess painted by Peter Mohrbacher and WLOP, rossdraws, digital painting",
  "portrait of a stunning beautiful explosion over the ocean by Peter Mohrbacher, character design, surrealism, vibrant palette",
  "a luminous orchid garden painted by Albert Bierstadt and Hubert Robert, oil on canvas, magical realism, luminous",
  "painting of a secret cottage in a luminous orchid garden by Albert Bierstadt and Jean Delville, artstation",
  "mystical painting of a cute dark orchid garden by Alexander Jansson",
  "stunning painting of a lone rusted imposing mech in a wheatfield by Simon Stålenhag and beeple, digital painting, soft render, moody palette",
  "an imposing mecha-samurai hybrid in a field of violet flowers by Gediminas Pranckevicius and beeple, dieselpunk aesthetic",
  "a landscape painting of retro diner outside los angeles by Peter Mohrbacher and Simon Stålenhag, retrowave noir",
  "a lighthouse on a cliffside overlooking the turbulent bay by Tyler Edlin and ivan aivazovsky",
  "cherry blossom tree next to a serene river by Ross Tran and Tyler Edlin, magical realism, impressionism, watercolor, award winnin",
  "a bioluminescent jellyfish over futuristic cityscape, deviantart, cinematic lighting, vibrant",
  "hyperrealism painting, underwater sea sponges, tending on deviantart, cinematic lighting, god rays, pastel palette, pastelwave",
  "impressionism painting by Bob Ross, volcano, lava, trees, boulders, obsidian, trending on artstation",
  "realism landscape oil painting, rusty dilapitated metal buildings, foggy ground, graffiti on buildings, vibrant",
  "magical realism painting of a lighting storm over the ocean by Ivan Aivazovsky dark night",
  "naturalism painting of vineyard, vibrant palette, bright sky, clouds",
  "landscape painting of a field of blue roses, a lone greenhouse in the field",
  "realism painting of a pack of wolves in a snowy field, snowing, twilight skies, aurora borealis, by Albert Bierstadt",
  "landscape painting of grassy field with many Pikachu by Albert Bierstadt, afternoon skies, vibrant, trees",
  "futuristic cyber city slums landscape by Liam Wong, highly detailed matte painting",
  "beautiful cyberpunk portrait by Liam Wong and Ross Tran, artstation, dark, contrasting, noir",
  "a ruined cathedral in a field of flowers by Dan Mumford, digital art, gothic art",
  "a ruined building on a field of flowers on a stormy day by Wayne Barlowe and Hans Bellmer, turbulent clouds, concept art, cinematic lighting",
  "a glass tower on a field of flowers landscape by Mike Winkelmann and Beeple, surrealism, futurism",
  "a singular glass tower in a field of flowers landscape by John Atkinson Grimshaw, highly detailed 3d matte painting",
  "massive subterranean galaxy in sprawling ancient ruins of atlantis, a dramatic matte painting by Tyler Edlin, trending on artstation, vivid and vibrant",
  "a stunning painting of a mystical glass tower in the town square by John Atkinson Grimshaw, highly detailed matte painting, nightscape",
  "an ominous painting of the Eiffel tower by Zdzisław Beksiński",
  "a beautiful portrait of mecha statue of liberty by  James Jean and Ross Tran",
  "a magic realism painting by Gediminas Pranckevicius depicting an abandoned building in a field of flowers landscape, vibrant, cinematic lighting",
  "watercolour image of hooded figure standing in small boat collecting orbs of light from a river",
  "a majestic glass tower in a serene oceanic landscape illustrated by john atkinson grimshaw and thomas kinkade, digital art, magic realism",
  "portrait of a stunning woman in los angeles by Peter Mohrbacher and Ross Tran, retrowave noir",
  "sinister abandoned factory building in a desolate landscape by Laurie Lipton and Patrick Woodroffe, withered roses, dramatic scenery, synthwave",
  "a painting of a person standing in front of a house, a matte painting by chris cold, cgsociety, neo-romanticism, matte painting, atmospheric, volumetric lighting",
  "a beautiful portrait of a vine blossom fairy by Ross Tran and Leonardo da Vinci, rossdraws, highly detailed digital painting",
  "a contemporary mansion in a field of flowers landscape by Ross Tran and Caspar David Friedrich, oil on canvas, dramatic scenery, moody palette",
  "a beautiful portrait of a woman by Ross Tran and Leonardo da Vinci, rossdraws, artstation, piercing gaze",
  "robotic android on a balcony pondering the baroque city, artstation, oil and canvas, nightscape, at night",
  "portrait of a brooding magic investigator woman, by Tom Bagshaw and Sophie Anderson and Antoine Blanchard, moody palette, oil on canvas, neon light illumination, noir",
  "aesthetic masterpiece vaporwave woman portrait painting by Antoine Blanchard and Vincent Callebaut",
  "architectural sci-fi brutalist monument, nightscape, surrealism, oil on canvas, award winning, contest winner, by John Atkinson Grimshaw and Thomas Kinkade",
  "steampunk brutalist structural steampunk victorian monument in a field of flowers, deviantart, oil on canvas, moody palette, cinematic lighting",
  "a stunning painting of vintage truck parked on a mountain overlook, vaporwave palette, matte painting, moody palette, deviantart",
  "giant blooming flower on the alien planet topology, render, by Beeple and Gilbert Williams, magical realism, artstation",
  "warm cottage on a black sand beach, digital art, surrealism, dark ominous lonely, oil on canvas, textured painting, american romanticism",
  "cold concrete brutalist spomenik monument in the grand canyon, by john harris and tyler edlin and caspar david friedrich, graphic novel style",
  "portrait of mysterious handsome noir spacetime detective by Dante Gabriel Rossetti and Edward Moran and Charlie Bowater, magical realism, cgsociety, artstation",
  "a vast planetary sci-fi city by Ansel Adams and Bernardo Bellotto, oil on canvas, artstation, dramatic scenery, masterpiece, aesthetic",
  "a stunning profile portrait of art deco empress, by Evelyn De Morgan and Ross Tran, rossdraws, fresco, piercing gaze, black hair",
  "a portrait of a character in a scenic environment by John Atkinson Grimshaw by RHADS and Gilbert Williams, artstation",
  "movie still from a dark city noir thriller sci-fi movie by Monet, vibrant, impressionism, artstation, HBO, warner brothers",
  "portrait of aesthetic angelic vaporwave noir woman, by John Watkiss, by John Atkinson Grimshaw, soft lighting, deviantart, contrasting, dark, character concept illustration",
  "an aesthetic closeup portrait of a noir woman with red hair painted by John Atkinson Grimshaw and Antoine Blanchard, autumn palette, artstation",
  "a lonely ship adrift in the endless ocean of time, digital art, distant birds, moody palette",
  "descent into infinite madness, surrealism, oil on canvas, texture painting, statement piece, artstation, dark ominous scene, digital art",
  "clockwork wizard tower in the woods, artstation, highly detailed impressionism, cinematic lighting, watercolor, masterpiece, aesthetic",
  "cat sitting on the street, well composed cityscape painting, oil on canvas, watercolor, highly detailed impressionist painting",
  "synthwave 1980 sports car on an Arctic landscape, artstation, by Jordan Grimmer and RHADS and Gilbert Williams",
  "aesthetic iridescent crumbling cottage on a cliff by the sea, oil on canvas, artstation, soft render",
  "aesthetic warrior sorceress in scale armor portrait by Raymond Swanland, cyberpunk, sci-fi cybernetic implants",
  "Lilith, ada Lovelace portrait, Deadpool, gothic, artstation, oil on canvas",
  "aesthetic angelic redhead woman stone portrait by Anna Dittmann and Harumi Hironaka and Filip Hodas, flowers, magical, artsy, impressionism",
  "aesthetic stunning portrait of a woman on the roof watching the sunset by Daniel F. Gerhartz and Liam Wong, nocturne, impressionism, noir aesthetic",
  "stunning portrait of a man at a piano by Daniel F. Gerhartz and Liam Wong, nocturne, impressionism, noir aesthetic, neon lights, dark, contrast",
  "stunning portrait of a woman in an office by Daniel F. Gerhartz and Liam Wong, nocturne, impressionism, noir aesthetic",
  "stunning portrait of a woman walking on the magnificent mile by Wadim Kashin and Liam Wong and Antoine Blanchard, impressionism, concept art, aesthetic, masterpiece",
  "nocturne impressionist noir of a mysterious detective on the streets by Antoine Blanchard, cityscape, monochromatic, rain reflections, octane soft render, vintage detective",
  "planetary megacity sci-fi city by Hugh Ferriss, masterpiece, dystopian, architectural structural design, contrasting",
  "a stunning portrait of samurai woman by Evelyn De Morgan and Ross Tran, rossdraws, fresco",
  "stunning renaissance fresco portrait, masterpiece, artstation, by Sandro Botticelli, by Sofonisba Anguissola",
  "a portrait of kyrickyoung, oil on canvas, artstation, by J. C. Leyendecker and Edmund Blair Leighton and Charlie Bowater, octane render, soft lighting, contrasting",
  "stunning futuristic sci-fi woman character concept digital art by Leonardo da Vinci and WLOP, surrealism, character illustration, fresco cracked paint, highly detailed sci-fi illustration, soft render",
  "abandoned crumbling shopping mall overgrown by flowers and vines by Tyler Edlin and Jean Delville and John Aktinson Grimshaw and Hubert Robert, german romanticism style, oil on canvas, cinematic lighting, vibrant, hdr, concept art, rain reflections, juxtaposition",
  "the grand canyon by Tyler Edlin and Jean Delville and John Aktinson Grimshaw and Hubert Robert, german romanticism style, oil on canvas, cinematic lighting, vibrant, concept art, gothic, contrasting",
  "chicago magnificent mile overgrown by vines and flowers by Tyler Edlin and Jean Delville and John Aktinson Grimshaw and Hubert Robert, german romanticism style, oil on canvas, cinematic lighting, vibrant, concept art, gothic, contrasting, nightscape",
  "woman ponders the rocky mountains by Jordan Grimmer and RHADS and Gilbert William",
  "majestic frost covered Bison closeup by Jordan Grimmer and RHADS and Gilbert Williams and albert bierstadt, hdr, 4k, snow fog, octane, soft render",
  "Chicago by Jordan Grimmer and RHADS and Gilbert Williams",
  "the rocky mountains by Jordan Grimmer and RHADS",
  "the streets of an abandoned crumbling city overgrown by flowers and vines by Jean Delville and John Aktinson Grimshaw and Hubert Robert, german romanticism style, oil on canvas, cinematic lighting, vibrant, hdr, concept art",
  "atompunk wizard tower in a field of flowers landscape by John Harris and RHADS and Gilbert Williams, highly detailed matte painting, hdr, concept art",
  "astronaut standing in a scenic field of flowers at sunset, synthwave, octane, soft render, artstation",
];
